### ISSUE TITLE
UBO example not rendering in 3D?

### ISSUE THREAD

**Issue by sunscreen** [miyanyan/learnopengl-qt#1]
Hi this is the result instead of the 4 cubes

![image](https://github.com/user-attachments/assets/f972003a-8290-44a8-a770-54f97b4c6fdb)

Any ideas what the problem could be?

**Comment by miyanyan** [comment]
Is this the original code? I clone the repo but it seems work well.
![image](https://github.com/user-attachments/assets/ad58f0b5-90f2-4b4f-b3f2-8a2e59fc4f58)

**Comment by sunscreen** [comment]
Hi sorry... I actually tracked down the culpit 

GL dosnt seem to like QSizePolicy ::MinimumExpanding on the gl widget.. i wanted to beable to switch off some other widgets in the layout and allow the gl window to expand when possible..

with out minimumExpanding 

![image](https://github.com/user-attachments/assets/4a2d72ed-d7bb-40a0-9775-423526ac63e3)

**Comment by sunscreen** [comment]
thanks 👍
